// <auto-generated />
namespace CHPOUTSRCMES.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_dlv_soa_t : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_dlv_soa_t));
        
        string IMigrationMetadata.Id
        {
            get { return "202009070735192_add_dlv_soa_t"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
