// <auto-generated />
namespace CHPOUTSRCMES.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fix_log_entry : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_log_entry));
        
        string IMigrationMetadata.Id
        {
            get { return "202011040354502_fix_log_entry"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
