// <auto-generated />
namespace CHPOUTSRCMES.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class merge_branch_pon : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(merge_branch_pon));
        
        string IMigrationMetadata.Id
        {
            get { return "202009090210025_merge_branch_pon"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
